api = "0.4"

[buildpack]
id = "heroku/clojure"
version = "0.0.86"
name = "Clojure"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]
shim_v2_tarball="https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/clojure-v86.tgz"

[metadata.release.docker]
repository="public.ecr.aws/r2f9u0w4/heroku-clojure-buildpack"
