api = "0.4"

[buildpack]
id = "heroku/clojure"
version = "0.0.86"
name = "Clojure"
homepage = "https://github.com/heroku/heroku-buildpack-clojure"
description = "Official Heroku buildpack for Clojure applications. It uses Leiningen for building."
keywords = ["clojure", "leiningen"]
licenses = ["MIT"]

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.shim]
tarball = "https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/clojure-v86.tgz"
sha256 = "c85cb7f4e10a2bc76fc9804d14842ea1021609a23d953359eed30cfd019560d1"

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/r2f9u0w4/heroku-clojure-buildpack"
