api = "0.4"

[buildpack]
id = "heroku/java-function"
version = "0.3.3"
name = "Java Function"
homepage = "https://github.com/heroku/buildpacks-jvm"
keywords = ["java", "function"]
licenses = ["MIT"]

[[order]]

[[order.group]]
id = "heroku/jvm"
version = "0.1.4"

[[order.group]]
id = "heroku/maven"
version = "0.2.1"

[[order.group]]
id = "heroku/jvm-function-invoker"
version = "0.2.3"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/r2f9u0w4/heroku-java-function-buildpack"
