api = "0.6"

[buildpack]
id = "heroku/gradle"
version = "2.0.0"
name = "Gradle"
homepage = "https://github.com/heroku/buildpacks-jvm/buildpacks/gradle"
description = "Official Heroku buildpack for Gradle applications."
keywords = ["java", "gradle"]

[[licenses]]
type = "BSD-3-Clause"

[[stacks]]
id = "*"
