version: 2.1

orbs:
  pack: buildpacks/pack@0.2.2

jobs:
  package-buildpack:
    parameters:
      package-toml:
        type: string
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker
      - pack/install-pack:
          version: 0.16.0
      - run: pack package-buildpack test --config << parameters.package-toml >>

  shell-linting:
    docker:
      - image: koalaman/shellcheck-alpine:v0.7.1
    steps:
      - run: "apk add git"
      # shfmt is currently (Jan 2021) only available in the edge community repository.
      - run: "apk add shfmt --repository=http://dl-3.alpinelinux.org/alpine/edge/community"
      - checkout
      - run:
          name: "shellcheck"
          command: "shfmt -f . | xargs shellcheck"
      - run:
          name: "shfmt"
          command: "shfmt -d ."

workflows:
  version: 2
  ci:
    jobs:
      - shell-linting
      - package-buildpack:
          matrix:
            parameters:
              package-toml: [ "meta-buildpacks/java/package.toml", "buildpacks/jvm/package.toml" ]
