api = "0.4"

[buildpack]
id = "heroku/jvm"
version = "0.1.4"
name = "JVM"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/r2f9u0w4/heroku-jvm-buildpack"
