api = "0.4"

[buildpack]
id = "heroku/scala"
version = "0.0.88"
name = "Scala"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]
shim_v2_tarball="https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/scala-v88.tgz"

[metadata.release.docker]
repository="public.ecr.aws/r2f9u0w4/heroku-scala-buildpack"
