api = "0.4"

[buildpack]
id = "heroku/jvm-function-invoker"
version = "0.2.5"
name = "JVM Function Invoker"
clear-env = true
homepage = "https://github.com/heroku/buildpacks-jvm"
keywords = ["java", "function"]

[[licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.runtime]
url = "https://repo1.maven.org/maven2/com/salesforce/functions/sf-fx-runtime-java-runtime/0.1.1-ea/sf-fx-runtime-java-runtime-0.1.1-ea-jar-with-dependencies.jar"
sha256 = "b30ba50b967944120da9262832ea89c403bfefb578efbf08196af725f5e94cd0"

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/r2f9u0w4/heroku-jvm-function-invoker-buildpack"
