api = "0.4"

[buildpack]
id = "heroku/jvm-function-invoker"
version = "0.2.8"
name = "JVM Function Invoker"
clear-env = true
homepage = "https://github.com/heroku/buildpacks-jvm"
keywords = ["java", "function"]

[[licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.runtime]
url = "https://repo1.maven.org/maven2/com/salesforce/functions/sf-fx-runtime-java-runtime/0.2.0/sf-fx-runtime-java-runtime-0.2.0-jar-with-dependencies.jar"
sha256 = "79e21528627928a96de28495480db38cb90d8cc2c43aae3d3eef213e7b78ba76"

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/r2f9u0w4/heroku-jvm-function-invoker-buildpack"
