api = "0.4"

[buildpack]
id = "heroku/maven"
version = "0.2.0"
name = "Maven"
clear-env = true

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

# this is to allow testing of other stack compatibility and is not a guarantee
[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata.release.docker]
repository="public.ecr.aws/r2f9u0w4/heroku-maven-buildpack"
