api = "0.4"

[buildpack]
id = "heroku/maven"
version = "0.1.1"
name = "Maven"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

# this is to allow testing of other stack compatibility and is not a guarantee
[[stacks]]
id = "io.buildpacks.stacks.bionic"
